"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import { useAuth } from "@/context/AuthContext";
import { createClient } from "@/lib/supabase/client";
import { Profile } from "@/types/profile";

type CollaborationRequest = { id: string; event_id: string; creator_id: string; title: string; description: string | null; members_needed: number; skills_needed: string[] | null; status: string; event: { name: string } | null; profile: Profile | null };

export default function RequestDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const supabase = useMemo(() => createClient(), []); const { user, loading: authLoading } = useAuth();
  const [request, setRequest] = useState<CollaborationRequest | null>(null); const [hasApplied, setHasApplied] = useState(false); const [accepted, setAccepted] = useState(0); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); const { data, error } = await supabase.from("requests").select("*, event:event_id(name), profile:creator_id(*)").eq("id", id).single(); if (!error && data) { setRequest(data as CollaborationRequest); const [acceptedResult, appliedResult] = await Promise.all([supabase.from("applications").select("*", { count: "exact", head: true }).eq("request_id", id).eq("status", "accepted"), user ? supabase.from("applications").select("id").eq("request_id", id).eq("applicant_id", user.id).maybeSingle() : Promise.resolve({ data: null })]); setAccepted(acceptedResult.count ?? 0); setHasApplied(Boolean(appliedResult.data)); } else setMessage("This collaboration request is unavailable."); setLoading(false); }, [id, supabase, user]);
  useEffect(() => { load(); }, [load]);
  async function apply(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!user) return router.push("/login"); setSaving(true); const { error } = await supabase.from("applications").insert({ request_id: id, applicant_id: user.id, message: new FormData(e.currentTarget).get("message"), status: "pending" }); setSaving(false); if (error) setMessage(error.code === "23505" ? "You have already applied to this request." : error.message); else { setHasApplied(true); setShowForm(false); setMessage("Application sent successfully."); } }
  if (loading) return <main className="min-h-screen bg-slate-50"><Navbar /><p className="py-24 text-center text-slate-500">Loading request…</p></main>;
  if (!request) return <main className="min-h-screen bg-slate-50"><Navbar /><p className="py-24 text-center text-slate-500">{message}</p></main>;
  const ownRequest = user?.id === request.creator_id; const unavailable = accepted >= request.members_needed || request.status !== "open"; const canApply = Boolean(user && !ownRequest && !hasApplied && !unavailable);
  return <main className="min-h-screen bg-slate-50"><Navbar /><section className="mx-auto max-w-4xl px-6 py-10"><a href={`/events/${request.event_id}`} className="text-sm font-semibold text-indigo-600">← Back to {request.event?.name || "event"}</a><article className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-indigo-600">{request.event?.name}</p><div className="mt-3 flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">{request.title}</h1><p className="mt-4 whitespace-pre-line leading-7 text-slate-600">{request.description}</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{request.status}</span></div><div className="mt-6 flex flex-wrap gap-2">{request.skills_needed?.map((skill) => <span key={skill} className="rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-medium text-indigo-700">{skill}</span>)}</div><p className="mt-5 text-sm text-slate-600">{request.members_needed} members needed · {accepted} accepted</p>{message && <p className="mt-5 rounded-lg bg-indigo-50 px-4 py-3 text-sm text-indigo-700">{message}</p>}<div className="mt-6">{!authLoading && !user && <button onClick={() => router.push("/login")} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Sign in to request to join</button>}{ownRequest && <p className="text-sm font-medium text-slate-500">You created this request.</p>}{hasApplied && <p className="text-sm font-medium text-emerald-700">You have already applied to join.</p>}{user && !ownRequest && unavailable && <p className="text-sm font-medium text-slate-500">This request is no longer accepting applications.</p>}{canApply && <button onClick={() => setShowForm(true)} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white hover:bg-indigo-700">Request to Join</button>}</div></article>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold text-slate-900">About the creator</h2><div className="mt-5 flex gap-4">{request.profile?.avatar_url ? <img src={request.profile.avatar_url} alt="" className="h-14 w-14 rounded-full object-cover" /> : <div className="grid h-14 w-14 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">{(request.profile?.full_name || "S")[0]}</div>}<div><h3 className="font-bold text-slate-900">{request.profile?.full_name || "Campus student"}</h3><p className="text-sm text-slate-600">{[request.profile?.course, request.profile?.year, request.profile?.college].filter(Boolean).join(" · ")}</p></div></div>{request.profile?.bio && <p className="mt-5 leading-7 text-slate-600">{request.profile.bio}</p>}<div className="mt-5 flex flex-wrap gap-2">{(Array.isArray(request.profile?.skills) ? request.profile.skills : []).map((skill) => <span key={skill} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700">{skill}</span>)}</div>{(request.profile?.github || request.profile?.linkedin) && <div className="mt-5 flex gap-4 text-sm font-semibold text-indigo-600">{request.profile.github && <a href={request.profile.github.startsWith("http") ? request.profile.github : `https://${request.profile.github}`} target="_blank" rel="noreferrer">GitHub</a>}{request.profile.linkedin && <a href={request.profile.linkedin.startsWith("http") ? request.profile.linkedin : `https://${request.profile.linkedin}`} target="_blank" rel="noreferrer">LinkedIn</a>}</div>}</section>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={apply} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-bold">Request to join</h2><button type="button" onClick={() => setShowForm(false)} className="text-slate-500">✕</button></div><label className="mt-5 block text-sm font-medium">Why should the team select you?<textarea required name="message" className="mt-2 min-h-32 w-full rounded-lg border border-slate-300 p-3" placeholder="Share relevant skills and experience." /></label><button disabled={saving} className="mt-5 w-full rounded-xl bg-indigo-600 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Sending…" : "Send application"}</button></form></div>}</section></main>;
}
